exports.countries = [
  {
    group: 0,
    countriesObj: [
      { name: 'Iran', code: 'IR' },
      { name: 'Sudan', code: 'SD' },
    ],
  },
  {
    group: 1,
    countriesObj: [
      { code: 'AF', name: 'Afghanistan' },
      { code: 'EG', name: 'Egypt' },
      { code: 'KG', name: 'Kyrgyzstan' },
      { code: 'LK', name: 'Sri Lanka' },
      { code: 'BI', name: 'Burundi' },
      { code: 'BT', name: 'Bhutan' },
      { code: 'GE', name: 'Georgia' },
      { code: 'LA', name: "Lao People's Democratic Republic" },
      { code: 'LB', name: 'Lebanon' },
      { code: 'LY', name: 'Libya' },
      { code: 'MM', name: 'Myanmar' },
      { code: 'PK', name: 'Pakistan' },
      { code: 'SL', name: 'Sierra Leone' },
      { code: 'TJ', name: 'Tajikistan' },
      { code: 'NP', name: 'Nepal' },
      { code: 'SR', name: 'Suriname' },
      { code: 'UZ', name: 'Uzbekistan' },
    ],
  },
  // ['🇦🇫', '🇪🇬', '🇰🇬', '🇱🇰', '🇧🇮', '🇧🇹', '🇬🇪', '🇱🇦', '🇱🇧', '🇱🇾', '🇲🇲', '🇵🇰', '🇸🇱', '🇹🇯', '🇳🇵', '🇸🇷', '🇺🇿'],
  {
    group: 2,
    countriesObj: [
      { code: 'BD', name: 'Bangladesh' },
      { code: 'BF', name: 'Burkina Faso' },
      { code: 'BG', name: 'Bulgaria' },
      { code: 'CO', name: 'Colombia' },
      { code: 'ET', name: 'Ethiopia' },
      { code: 'KH', name: 'Cambodia' },
      { code: 'AM', name: 'Armenia' },
      { code: 'AO', name: 'Angola' },
      { code: 'AZ', name: 'Azerbaijan' },
      { code: 'BO', name: 'Bolivia, Plurinational State of' },
      { code: 'BY', name: 'Belarus' },
      { code: 'DZ', name: 'Algeria' },
      { code: 'ER', name: 'Eritrea' },
      { code: 'GH', name: 'Ghana' },
      { code: 'GM', name: 'Gambia' },
      { code: 'GW', name: 'Guinea-Bissau' },
      { code: 'GY', name: 'Guyana' },
      { code: 'ID', name: 'Indonesia' },
      { code: 'KE', name: 'Kenya' },
      { code: 'KZ', name: 'Kazakhstan' },
      { code: 'MD', name: 'Moldova, Republic of' },
      { code: 'MK', name: 'North Macedonia' },
      { code: 'ML', name: 'Mali' },
      { code: 'MW', name: 'Malawi' },
      { code: 'MY', name: 'Malaysia' },
      { code: 'MZ', name: 'Mozambique' },
      { code: 'NG', name: 'Nigeria' },
      { code: 'NI', name: 'Nicaragua' },
      { code: 'PH', name: 'Philippines' },
      { code: 'PY', name: 'Paraguay' },
      { code: 'RU', name: 'Russian Federation' },
      { code: 'RW', name: 'Rwanda' },
      { code: 'TH', name: 'Thailand' },
      { code: 'TZ', name: 'Tanzania, United Republic of' },
      { code: 'UA', name: 'Ukraine' },
      { code: 'UG', name: 'Uganda' },
      { code: 'VN', name: 'Viet Nam' },
      { code: 'IN', name: 'India' },
      { code: 'MG', name: 'Madagascar' },
      { code: 'MN', name: 'Mongolia' },
      { code: 'MR', name: 'Mauritania' },
      { code: 'MU', name: 'Mauritius' },
      { code: 'SO', name: 'Somalia' },
      { code: 'TL', name: 'Timor-Leste' },
      { code: 'TN', name: 'Tunisia' },
      { code: 'TR', name: 'Türkiye' },
      { code: 'ZM', name: 'Zambia' },
    ],
  },
  {
    group: 3,
    countriesObj: [
      { code: 'AL', name: 'Albania' },
      { code: 'BA', name: 'Bosnia and Herzegovina' },
      { code: 'BG', name: 'Bulgaria' },
      { code: 'BW', name: 'Botswana' },
      { code: 'CM', name: 'Cameroon' },
      { code: 'CV', name: 'Cabo Verde' },
      { code: 'GQ', name: 'Equatorial Guinea' },
      { code: 'HN', name: 'Honduras' },
      { code: 'JO', name: 'Jordan' },
      { code: 'AR', name: 'Argentina' },
      { code: 'BH', name: 'Bahrain' },
      { code: 'BR', name: 'Brazil' },
      { code: 'CD', name: 'Congo, Democratic Republic of the' },
      { code: 'CI', name: "Côte d'Ivoire" },
      { code: 'DO', name: 'Dominican Republic' },
      { code: 'FJ', name: 'Fiji' },
      { code: 'GN', name: 'Guinea' },
      { code: 'IQ', name: 'Iraq' },
      { code: 'JM', name: 'Jamaica' },
      { code: 'KM', name: 'Comoros' },
      { code: 'LR', name: 'Liberia' },
      { code: 'LS', name: 'Lesotho' },
      { code: 'ME', name: 'Montenegro' },
      { code: 'OM', name: 'Oman' },
      { code: 'PA', name: 'Panama' },
      { code: 'MX', name: 'Mexico' },
      { code: 'NA', name: 'Namibia' },
      { code: 'SA', name: 'Saudi Arabia' },
      { code: 'PE', name: 'Peru' },
      { code: 'PL', name: 'Poland' },
      { code: 'RO', name: 'Romania' },
      { code: 'RS', name: 'Serbia' },
      { code: 'SC', name: 'Seychelles' },
      { code: 'SN', name: 'Senegal' },
      { code: 'SV', name: 'El Salvador' },
      { code: 'TM', name: 'Turkmenistan' },
      { code: 'TW', name: 'Taiwan, Province of China' },
      { code: 'BN', name: 'Brunei Darussalam' },
      { code: 'MA', name: 'Morocco' },
      { code: 'MV', name: 'Maldives' },
      { code: 'NE', name: 'Niger' },
      { code: 'SZ', name: 'Eswatini' },
      { code: 'TD', name: 'Chad' },
      { code: 'TG', name: 'Togo' },
      { code: 'YE', name: 'Yemen' },
      { code: 'ZA', name: 'South Africa' },
    ],
  },
  {
    group: 4,
    countriesObj: [
      { code: 'AE', name: 'United Arab Emirates' },
      { code: 'DJ', name: 'Djibouti' },
      { code: 'EC', name: 'Ecuador' },
      { code: 'GT', name: 'Guatemala' },
      { code: 'HR', name: 'Croatia' },
      { code: 'LT', name: 'Lithuania' },
      { code: 'CF', name: 'Central African Republic' },
      { code: 'CL', name: 'Chile' },
      { code: 'CR', name: 'Costa Rica' },
      { code: 'CZ', name: 'Czechia' },
      { code: 'GA', name: 'Gabon' },
      { code: 'GD', name: 'Grenada' },
      { code: 'HT', name: 'Haiti' },
      { code: 'HU', name: 'Hungary' },
      { code: 'KW', name: 'Kuwait' },
      { code: 'LV', name: 'Latvia' },
      { code: 'ST', name: 'Sao Tome and Principe' },
      { code: 'TT', name: 'Trinidad and Tobago' },
      { code: 'VC', name: 'Saint Vincent and the Grenadines' },
    ],
  },
  {
    group: 5,
    countriesObj: [
      { code: 'EE', name: 'Estonia' },
      { code: 'GR', name: 'Greece' },
      { code: 'KN', name: 'Saint Kitts and Nevis' },
      { code: 'BZ', name: 'Belize' },
      { code: 'CG', name: 'Congo' },
      { code: 'CN', name: 'China' },
      { code: 'KI', name: 'Kiribati' },
      { code: 'LC', name: 'Saint Lucia' },
      { code: 'PT', name: 'Portugal' },
      { code: 'MT', name: 'Malta' },
      { code: 'QA', name: 'Qatar' },
      { code: 'SI', name: 'Slovenia' },
      { code: 'SK', name: 'Slovakia' },
      { code: 'PG', name: 'Papua New Guinea' },
      { code: 'SG', name: 'Singapore' },
      { code: 'DM', name: 'Dominica' },
      { code: 'MO', name: 'Macao' },
      { code: 'TO', name: 'Tonga' },
      { code: 'UY', name: 'Uruguay' },
      { code: 'VE', name: 'Venezuela, Bolivarian Republic of' },
      { code: 'WS', name: 'Samoa' },
    ],
  },
  {
    group: 6,
    countriesObj: [
      { code: 'ES', name: 'Spain' },
      { code: 'HK', name: 'Hong Kong' },
      { code: 'AW', name: 'Aruba' },
      { code: 'CY', name: 'Cyprus' },
      { code: 'IT', name: 'Italy' },
      { code: 'KR', name: 'Korea, Republic of' },
      { code: 'AG', name: 'Antigua and Barbuda' },
      { code: 'SM', name: 'San Marino' },
      { code: 'ZW', name: 'Zimbabwe' },
    ],
  },
  {
    group: 7,
    countriesObj: [
      { code: 'BE', name: 'Belgium' },
      { code: 'BS', name: 'Bahamas' },
      { code: 'DE', name: 'Germany' },
      { code: 'FR', name: 'France' },
      { code: 'PW', name: 'Palau' },
      { code: 'SB', name: 'Solomon Islands' },
      { code: 'NR', name: 'Nauru' },
    ],
  },
  {
    group: 8,
    countriesObj: [
      { code: 'AT', name: 'Austria' },
      { code: 'CA', name: 'Canada' },
      {
        code: 'GB',
        name: 'United Kingdom of Great Britain and Northern Ireland',
      },
      { code: 'IE', name: 'Ireland' },
      { code: 'JP', name: 'Japan' },
      { code: 'FI', name: 'Finland' },
      { code: 'FM', name: 'Micronesia, Federated States of' },
      { code: 'PR', name: 'Puerto Rico' },
      { code: 'NL', name: 'Netherlands' },
      { code: 'US', name: 'United States of America' },
      { code: 'MH', name: 'Marshall Islands' },
      { code: 'SS', name: 'South Sudan' },
    ],
  },
  {
    group: 9,
    countriesObj: [
      { code: 'AU', name: 'Australia' },
      { code: 'LU', name: 'Luxembourg' },
      { code: 'DK', name: 'Denmark' },
      { code: 'SE', name: 'Sweden' },
      { code: 'VU', name: 'Vanuatu' },
      { code: 'NZ', name: 'New Zealand' },
      { code: 'TV', name: 'Tuvalu' },
    ],
  },
  {
    group: 10,
    countriesObj: [
      { code: 'IL', name: 'Israel' },
      { code: 'BB', name: 'Barbados' },
      { code: 'IS', name: 'Iceland' },
      { code: 'NO', name: 'Norway' },
    ],
  },
  {
    group: 11,
    countriesObj: [{ code: 'CH', name: 'Switzerland' }],
  },
];

exports.getByCountryName = {
  Iran: { code: 'IR', group: 0 },
  Sudan: { code: 'SD', group: 0 },
  Afghanistan: { code: 'AF', group: 1 },
  Egypt: { code: 'EG', group: 1 },
  Kyrgyzstan: { code: 'KG', group: 1 },
  'Sri Lanka': { code: 'LK', group: 1 },
  Burundi: { code: 'BI', group: 1 },
  Bhutan: { code: 'BT', group: 1 },
  Georgia: { code: 'GE', group: 1 },
  "Lao People's Democratic Republic": { code: 'LA', group: 1 },
  Lebanon: { code: 'LB', group: 1 },
  Libya: { code: 'LY', group: 1 },
  Myanmar: { code: 'MM', group: 1 },
  Pakistan: { code: 'PK', group: 1 },
  'Sierra Leone': { code: 'SL', group: 1 },
  Tajikistan: { code: 'TJ', group: 1 },
  Nepal: { code: 'NP', group: 1 },
  Suriname: { code: 'SR', group: 1 },
  Uzbekistan: { code: 'UZ', group: 1 },
  Bangladesh: { code: 'BD', group: 2 },
  'Burkina Faso': { code: 'BF', group: 2 },
  Bulgaria: { code: 'BG', group: 3 },
  Colombia: { code: 'CO', group: 2 },
  Ethiopia: { code: 'ET', group: 2 },
  Cambodia: { code: 'KH', group: 2 },
  Armenia: { code: 'AM', group: 2 },
  Angola: { code: 'AO', group: 2 },
  Azerbaijan: { code: 'AZ', group: 2 },
  'Bolivia, Plurinational State of': { code: 'BO', group: 2 },
  Belarus: { code: 'BY', group: 2 },
  Algeria: { code: 'DZ', group: 2 },
  Eritrea: { code: 'ER', group: 2 },
  Ghana: { code: 'GH', group: 2 },
  Gambia: { code: 'GM', group: 2 },
  'Guinea-Bissau': { code: 'GW', group: 2 },
  Guyana: { code: 'GY', group: 2 },
  Indonesia: { code: 'ID', group: 2 },
  Kenya: { code: 'KE', group: 2 },
  Kazakhstan: { code: 'KZ', group: 2 },
  'Moldova, Republic of': { code: 'MD', group: 2 },
  'North Macedonia': { code: 'MK', group: 2 },
  Mali: { code: 'ML', group: 2 },
  Malawi: { code: 'MW', group: 2 },
  Malaysia: { code: 'MY', group: 2 },
  Mozambique: { code: 'MZ', group: 2 },
  Nigeria: { code: 'NG', group: 2 },
  Nicaragua: { code: 'NI', group: 2 },
  Philippines: { code: 'PH', group: 2 },
  Paraguay: { code: 'PY', group: 2 },
  'Russian Federation': { code: 'RU', group: 2 },
  Rwanda: { code: 'RW', group: 2 },
  Thailand: { code: 'TH', group: 2 },
  'Tanzania, United Republic of': { code: 'TZ', group: 2 },
  Ukraine: { code: 'UA', group: 2 },
  Uganda: { code: 'UG', group: 2 },
  'Viet Nam': { code: 'VN', group: 2 },
  India: { code: 'IN', group: 2 },
  Madagascar: { code: 'MG', group: 2 },
  Mongolia: { code: 'MN', group: 2 },
  Mauritania: { code: 'MR', group: 2 },
  Mauritius: { code: 'MU', group: 2 },
  Somalia: { code: 'SO', group: 2 },
  'Timor-Leste': { code: 'TL', group: 2 },
  Tunisia: { code: 'TN', group: 2 },
  Türkiye: { code: 'TR', group: 2 },
  Zambia: { code: 'ZM', group: 2 },
  Albania: { code: 'AL', group: 3 },
  'Bosnia and Herzegovina': { code: 'BA', group: 3 },
  Botswana: { code: 'BW', group: 3 },
  Cameroon: { code: 'CM', group: 3 },
  'Cabo Verde': { code: 'CV', group: 3 },
  'Equatorial Guinea': { code: 'GQ', group: 3 },
  Honduras: { code: 'HN', group: 3 },
  Jordan: { code: 'JO', group: 3 },
  Argentina: { code: 'AR', group: 3 },
  Bahrain: { code: 'BH', group: 3 },
  Brazil: { code: 'BR', group: 3 },
  'Congo, Democratic Republic of the': { code: 'CD', group: 3 },
  "Côte d'Ivoire": { code: 'CI', group: 3 },
  'Dominican Republic': { code: 'DO', group: 3 },
  Fiji: { code: 'FJ', group: 3 },
  Guinea: { code: 'GN', group: 3 },
  Iraq: { code: 'IQ', group: 3 },
  Jamaica: { code: 'JM', group: 3 },
  Comoros: { code: 'KM', group: 3 },
  Liberia: { code: 'LR', group: 3 },
  Lesotho: { code: 'LS', group: 3 },
  Montenegro: { code: 'ME', group: 3 },
  Oman: { code: 'OM', group: 3 },
  Panama: { code: 'PA', group: 3 },
  Mexico: { code: 'MX', group: 3 },
  Namibia: { code: 'NA', group: 3 },
  'Saudi Arabia': { code: 'SA', group: 3 },
  Peru: { code: 'PE', group: 3 },
  Poland: { code: 'PL', group: 3 },
  Romania: { code: 'RO', group: 3 },
  Serbia: { code: 'RS', group: 3 },
  Seychelles: { code: 'SC', group: 3 },
  Senegal: { code: 'SN', group: 3 },
  'El Salvador': { code: 'SV', group: 3 },
  Turkmenistan: { code: 'TM', group: 3 },
  'Taiwan, Province of China': { code: 'TW', group: 3 },
  'Brunei Darussalam': { code: 'BN', group: 3 },
  Morocco: { code: 'MA', group: 3 },
  Maldives: { code: 'MV', group: 3 },
  Niger: { code: 'NE', group: 3 },
  Eswatini: { code: 'SZ', group: 3 },
  Chad: { code: 'TD', group: 3 },
  Togo: { code: 'TG', group: 3 },
  Yemen: { code: 'YE', group: 3 },
  'South Africa': { code: 'ZA', group: 3 },
  'United Arab Emirates': { code: 'AE', group: 4 },
  Djibouti: { code: 'DJ', group: 4 },
  Ecuador: { code: 'EC', group: 4 },
  Guatemala: { code: 'GT', group: 4 },
  Croatia: { code: 'HR', group: 4 },
  Lithuania: { code: 'LT', group: 4 },
  'Central African Republic': { code: 'CF', group: 4 },
  Chile: { code: 'CL', group: 4 },
  'Costa Rica': { code: 'CR', group: 4 },
  Czechia: { code: 'CZ', group: 4 },
  Gabon: { code: 'GA', group: 4 },
  Grenada: { code: 'GD', group: 4 },
  Haiti: { code: 'HT', group: 4 },
  Hungary: { code: 'HU', group: 4 },
  Kuwait: { code: 'KW', group: 4 },
  Latvia: { code: 'LV', group: 4 },
  'Sao Tome and Principe': { code: 'ST', group: 4 },
  'Trinidad and Tobago': { code: 'TT', group: 4 },
  'Saint Vincent and the Grenadines': { code: 'VC', group: 4 },
  Estonia: { code: 'EE', group: 5 },
  Greece: { code: 'GR', group: 5 },
  'Saint Kitts and Nevis': { code: 'KN', group: 5 },
  Belize: { code: 'BZ', group: 5 },
  Congo: { code: 'CG', group: 5 },
  China: { code: 'CN', group: 5 },
  Kiribati: { code: 'KI', group: 5 },
  'Saint Lucia': { code: 'LC', group: 5 },
  Portugal: { code: 'PT', group: 5 },
  Malta: { code: 'MT', group: 5 },
  Qatar: { code: 'QA', group: 5 },
  Slovenia: { code: 'SI', group: 5 },
  Slovakia: { code: 'SK', group: 5 },
  'Papua New Guinea': { code: 'PG', group: 5 },
  Singapore: { code: 'SG', group: 5 },
  Dominica: { code: 'DM', group: 5 },
  Macao: { code: 'MO', group: 5 },
  Tonga: { code: 'TO', group: 5 },
  Uruguay: { code: 'UY', group: 5 },
  'Venezuela, Bolivarian Republic of': { code: 'VE', group: 5 },
  Samoa: { code: 'WS', group: 5 },
  Spain: { code: 'ES', group: 6 },
  'Hong Kong': { code: 'HK', group: 6 },
  Aruba: { code: 'AW', group: 6 },
  Cyprus: { code: 'CY', group: 6 },
  Italy: { code: 'IT', group: 6 },
  'Korea, Republic of': { code: 'KR', group: 6 },
  'Antigua and Barbuda': { code: 'AG', group: 6 },
  'San Marino': { code: 'SM', group: 6 },
  Zimbabwe: { code: 'ZW', group: 6 },
  Belgium: { code: 'BE', group: 7 },
  Bahamas: { code: 'BS', group: 7 },
  Germany: { code: 'DE', group: 7 },
  France: { code: 'FR', group: 7 },
  Palau: { code: 'PW', group: 7 },
  'Solomon Islands': { code: 'SB', group: 7 },
  Nauru: { code: 'NR', group: 7 },
  Austria: { code: 'AT', group: 7 },
  Canada: { code: 'CA', group: 7 },
  'United Kingdom of Great Britain and Northern Ireland': {
    code: 'GB',
    group: 7,
  },
  Ireland: { code: 'IE', group: 7 },
  Japan: { code: 'JP', group: 7 },
  Finland: { code: 'FI', group: 7 },
  'Micronesia, Federated States of': { code: 'FM', group: 7 },
  'Puerto Rico': { code: 'PR', group: 7 },
  Netherlands: { code: 'NL', group: 7 },
  'United States of America': { code: 'US', group: 7 },
  'Marshall Islands': { code: 'MH', group: 7 },
  'South Sudan': { code: 'SS', group: 7 },
  Australia: { code: 'AU', group: 9 },
  Luxembourg: { code: 'LU', group: 9 },
  Denmark: { code: 'DK', group: 9 },
  Sweden: { code: 'SE', group: 9 },
  Vanuatu: { code: 'VU', group: 9 },
  'New Zealand': { code: 'NZ', group: 9 },
  Tuvalu: { code: 'TV', group: 9 },
  Israel: { code: 'IL', group: 10 },
  Barbados: { code: 'BB', group: 10 },
  Iceland: { code: 'IS', group: 10 },
  Norway: { code: 'NO', group: 10 },
  Switzerland: { code: 'CH', group: 11 },
};

exports.getByCountryCode = {
  IR: { name: 'Iran', group: 0 },
  SD: { name: 'Sudan', group: 0 },
  AF: { name: 'Afghanistan', group: 1 },
  EG: { name: 'Egypt', group: 1 },
  KG: { name: 'Kyrgyzstan', group: 1 },
  LK: { name: 'Sri Lanka', group: 1 },
  BI: { name: 'Burundi', group: 1 },
  BT: { name: 'Bhutan', group: 1 },
  GE: { name: 'Georgia', group: 1 },
  LA: { name: "Lao People's Democratic Republic", group: 1 },
  LB: { name: 'Lebanon', group: 1 },
  LY: { name: 'Libya', group: 1 },
  MM: { name: 'Myanmar', group: 1 },
  PK: { name: 'Pakistan', group: 1 },
  SL: { name: 'Sierra Leone', group: 1 },
  TJ: { name: 'Tajikistan', group: 1 },
  NP: { name: 'Nepal', group: 1 },
  SR: { name: 'Suriname', group: 1 },
  UZ: { name: 'Uzbekistan', group: 1 },
  BD: { name: 'Bangladesh', group: 2 },
  BF: { name: 'Burkina Faso', group: 2 },
  BG: { name: 'Bulgaria', group: 3 },
  CO: { name: 'Colombia', group: 2 },
  ET: { name: 'Ethiopia', group: 2 },
  KH: { name: 'Cambodia', group: 2 },
  AM: { name: 'Armenia', group: 2 },
  AO: { name: 'Angola', group: 2 },
  AZ: { name: 'Azerbaijan', group: 2 },
  BO: { name: 'Bolivia, Plurinational State of', group: 2 },
  BY: { name: 'Belarus', group: 2 },
  DZ: { name: 'Algeria', group: 2 },
  ER: { name: 'Eritrea', group: 2 },
  GH: { name: 'Ghana', group: 2 },
  GM: { name: 'Gambia', group: 2 },
  GW: { name: 'Guinea-Bissau', group: 2 },
  GY: { name: 'Guyana', group: 2 },
  ID: { name: 'Indonesia', group: 2 },
  KE: { name: 'Kenya', group: 2 },
  KZ: { name: 'Kazakhstan', group: 2 },
  MD: { name: 'Moldova, Republic of', group: 2 },
  MK: { name: 'North Macedonia', group: 2 },
  ML: { name: 'Mali', group: 2 },
  MW: { name: 'Malawi', group: 2 },
  MY: { name: 'Malaysia', group: 2 },
  MZ: { name: 'Mozambique', group: 2 },
  NG: { name: 'Nigeria', group: 2 },
  NI: { name: 'Nicaragua', group: 2 },
  PH: { name: 'Philippines', group: 2 },
  PY: { name: 'Paraguay', group: 2 },
  RU: { name: 'Russian Federation', group: 2 },
  RW: { name: 'Rwanda', group: 2 },
  TH: { name: 'Thailand', group: 2 },
  TZ: { name: 'Tanzania, United Republic of', group: 2 },
  UA: { name: 'Ukraine', group: 2 },
  UG: { name: 'Uganda', group: 2 },
  VN: { name: 'Viet Nam', group: 2 },
  IN: { name: 'India', group: 2 },
  MG: { name: 'Madagascar', group: 2 },
  MN: { name: 'Mongolia', group: 2 },
  MR: { name: 'Mauritania', group: 2 },
  MU: { name: 'Mauritius', group: 2 },
  SO: { name: 'Somalia', group: 2 },
  TL: { name: 'Timor-Leste', group: 2 },
  TN: { name: 'Tunisia', group: 2 },
  TR: { name: 'Türkiye', group: 2 },
  ZM: { name: 'Zambia', group: 2 },
  AL: { name: 'Albania', group: 3 },
  BA: { name: 'Bosnia and Herzegovina', group: 3 },
  BW: { name: 'Botswana', group: 3 },
  CM: { name: 'Cameroon', group: 3 },
  CV: { name: 'Cabo Verde', group: 3 },
  GQ: { name: 'Equatorial Guinea', group: 3 },
  HN: { name: 'Honduras', group: 3 },
  JO: { name: 'Jordan', group: 3 },
  AR: { name: 'Argentina', group: 3 },
  BH: { name: 'Bahrain', group: 3 },
  BR: { name: 'Brazil', group: 3 },
  CD: { name: 'Congo, Democratic Republic of the', group: 3 },
  CI: { name: "Côte d'Ivoire", group: 3 },
  DO: { name: 'Dominican Republic', group: 3 },
  FJ: { name: 'Fiji', group: 3 },
  GN: { name: 'Guinea', group: 3 },
  IQ: { name: 'Iraq', group: 3 },
  JM: { name: 'Jamaica', group: 3 },
  KM: { name: 'Comoros', group: 3 },
  LR: { name: 'Liberia', group: 3 },
  LS: { name: 'Lesotho', group: 3 },
  ME: { name: 'Montenegro', group: 3 },
  OM: { name: 'Oman', group: 3 },
  PA: { name: 'Panama', group: 3 },
  MX: { name: 'Mexico', group: 3 },
  NA: { name: 'Namibia', group: 3 },
  SA: { name: 'Saudi Arabia', group: 3 },
  PE: { name: 'Peru', group: 3 },
  PL: { name: 'Poland', group: 3 },
  RO: { name: 'Romania', group: 3 },
  RS: { name: 'Serbia', group: 3 },
  SC: { name: 'Seychelles', group: 3 },
  SN: { name: 'Senegal', group: 3 },
  SV: { name: 'El Salvador', group: 3 },
  TM: { name: 'Turkmenistan', group: 3 },
  TW: { name: 'Taiwan, Province of China', group: 3 },
  BN: { name: 'Brunei Darussalam', group: 3 },
  MA: { name: 'Morocco', group: 3 },
  MV: { name: 'Maldives', group: 3 },
  NE: { name: 'Niger', group: 3 },
  SZ: { name: 'Eswatini', group: 3 },
  TD: { name: 'Chad', group: 3 },
  TG: { name: 'Togo', group: 3 },
  YE: { name: 'Yemen', group: 3 },
  ZA: { name: 'South Africa', group: 3 },
  AE: { name: 'United Arab Emirates', group: 4 },
  DJ: { name: 'Djibouti', group: 4 },
  EC: { name: 'Ecuador', group: 4 },
  GT: { name: 'Guatemala', group: 4 },
  HR: { name: 'Croatia', group: 4 },
  LT: { name: 'Lithuania', group: 4 },
  CF: { name: 'Central African Republic', group: 4 },
  CL: { name: 'Chile', group: 4 },
  CR: { name: 'Costa Rica', group: 4 },
  CZ: { name: 'Czechia', group: 4 },
  GA: { name: 'Gabon', group: 4 },
  GD: { name: 'Grenada', group: 4 },
  HT: { name: 'Haiti', group: 4 },
  HU: { name: 'Hungary', group: 4 },
  KW: { name: 'Kuwait', group: 4 },
  LV: { name: 'Latvia', group: 4 },
  ST: { name: 'Sao Tome and Principe', group: 4 },
  TT: { name: 'Trinidad and Tobago', group: 4 },
  VC: { name: 'Saint Vincent and the Grenadines', group: 4 },
  EE: { name: 'Estonia', group: 5 },
  GR: { name: 'Greece', group: 5 },
  KN: { name: 'Saint Kitts and Nevis', group: 5 },
  BZ: { name: 'Belize', group: 5 },
  CG: { name: 'Congo', group: 5 },
  CN: { name: 'China', group: 5 },
  KI: { name: 'Kiribati', group: 5 },
  LC: { name: 'Saint Lucia', group: 5 },
  PT: { name: 'Portugal', group: 5 },
  MT: { name: 'Malta', group: 5 },
  QA: { name: 'Qatar', group: 5 },
  SI: { name: 'Slovenia', group: 5 },
  SK: { name: 'Slovakia', group: 5 },
  PG: { name: 'Papua New Guinea', group: 5 },
  SG: { name: 'Singapore', group: 5 },
  DM: { name: 'Dominica', group: 5 },
  MO: { name: 'Macao', group: 5 },
  TO: { name: 'Tonga', group: 5 },
  UY: { name: 'Uruguay', group: 5 },
  VE: { name: 'Venezuela, Bolivarian Republic of', group: 5 },
  WS: { name: 'Samoa', group: 5 },
  ES: { name: 'Spain', group: 6 },
  HK: { name: 'Hong Kong', group: 6 },
  AW: { name: 'Aruba', group: 6 },
  CY: { name: 'Cyprus', group: 6 },
  IT: { name: 'Italy', group: 6 },
  KR: { name: 'Korea, Republic of', group: 6 },
  AG: { name: 'Antigua and Barbuda', group: 6 },
  SM: { name: 'San Marino', group: 6 },
  ZW: { name: 'Zimbabwe', group: 6 },
  BE: { name: 'Belgium', group: 7 },
  BS: { name: 'Bahamas', group: 7 },
  DE: { name: 'Germany', group: 7 },
  FR: { name: 'France', group: 7 },
  PW: { name: 'Palau', group: 7 },
  SB: { name: 'Solomon Islands', group: 7 },
  NR: { name: 'Nauru', group: 7 },
  AT: { name: 'Austria', group: 7 },
  CA: { name: 'Canada', group: 7 },
  GB: {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    group: 7,
  },
  IE: { name: 'Ireland', group: 7 },
  JP: { name: 'Japan', group: 7 },
  FI: { name: 'Finland', group: 7 },
  FM: { name: 'Micronesia, Federated States of', group: 7 },
  PR: { name: 'Puerto Rico', group: 7 },
  NL: { name: 'Netherlands', group: 7 },
  US: { name: 'United States of America', group: 7 },
  MH: { name: 'Marshall Islands', group: 7 },
  SS: { name: 'South Sudan', group: 7 },
  AU: { name: 'Australia', group: 9 },
  LU: { name: 'Luxembourg', group: 9 },
  DK: { name: 'Denmark', group: 9 },
  SE: { name: 'Sweden', group: 9 },
  VU: { name: 'Vanuatu', group: 9 },
  NZ: { name: 'New Zealand', group: 9 },
  TV: { name: 'Tuvalu', group: 9 },
  IL: { name: 'Israel', group: 10 },
  BB: { name: 'Barbados', group: 10 },
  IS: { name: 'Iceland', group: 10 },
  NO: { name: 'Norway', group: 10 },
  CH: { name: 'Switzerland', group: 11 },
};

// export const codes = [
//     ['🇮🇷', '🇸🇩'],

//     ['🇦🇫', '🇪🇬', '🇰🇬', '🇱🇰', '🇧🇮', '🇧🇹', '🇬🇪', '🇱🇦', '🇱🇧', '🇱🇾', '🇲🇲', '🇵🇰', '🇸🇱', '🇹🇯', '🇳🇵', '🇸🇷', '🇺🇿'],

//     [
//         '🇧🇩',
//         '🇧🇫',
//         '🇧🇯',
//         '🇨🇴',
//         '🇪🇹',
//         '🇰🇭',
//         '🇦🇲',
//         '🇦🇴',
//         '🇦🇿',
//         '🇧🇴',
//         '🇧🇾',
//         '🇩🇿',
//         '🇪🇷',
//         '🇬🇭',
//         '🇬🇲',
//         '🇬🇼',
//         '🇬🇾',
//         '🇮🇩',
//         '🇰🇪',
//         '🇰🇿',
//         '🇲🇩',
//         '🇲🇰',
//         '🇲🇱',
//         '🇲🇼',
//         '🇲🇾',
//         '🇲🇿',
//         '🇳🇬',
//         '🇳🇮',
//         '🇵🇭',
//         '🇵🇾',
//         '🇷🇺',
//         '🇷🇼',
//         '🇹🇭',
//         '🇹🇿',
//         '🇺🇦',
//         '🇺🇬',
//         '🇻🇳',
//         '🇮🇳',
//         '🇲🇬',
//         '🇲🇳',
//         '🇲🇷',
//         '🇲🇺',
//         '🇸🇴',
//         '🇹🇱',
//         '🇹🇳',
//         '🇹🇷',
//         '🇿🇲'
//     ],

//     [
//         '🇦🇱',
//         '🇧🇦',
//         '🇧🇬',
//         '🇧🇼',
//         '🇨🇲',
//         '🇨🇻',
//         '🇬🇶',
//         '🇭🇳',
//         '🇯🇴',
//         '🇦🇷',
//         '🇧🇭',
//         '🇧🇷',
//         '🇨🇩',
//         '🇨🇮',
//         '🇩🇴',
//         '🇫🇯',
//         '🇬🇳',
//         '🇮🇶',
//         '🇯🇲',
//         '🇰🇲',
//         '🇱🇷',
//         '🇱🇸',
//         '🇲🇪',
//         '🇴🇲',
//         '🇵🇦',
//         '🇲🇽',
//         '🇳🇦',
//         '🇸🇦',
//         '🇵🇪',
//         '🇵🇱',
//         '🇷🇴',
//         '🇷🇸',
//         '🇸🇨',
//         '🇸🇳',
//         '🇸🇻',
//         '🇹🇲',
//         '🇹🇼',
//         '🇧🇳',
//         '🇲🇦',
//         '🇲🇻',
//         '🇳🇪',
//         '🇸🇿',
//         '🇹🇩',
//         '🇹🇬',
//         '🇾🇪',
//         '🇿🇦'
//     ],
//     ['🇦🇪', '🇩🇯', '🇪🇨', '🇬🇹', '🇭🇷', '🇱🇹', '🇨🇫', '🇨🇱', '🇨🇷', '🇨🇿', '🇬🇦', '🇬🇩', '🇭🇹', '🇭🇺', '🇰🇼', '🇱🇻', '🇸🇹', '🇹🇹', '🇻🇨'],
//     ['🇪🇪', '🇬🇷', '🇰🇳', '🇧🇿', '🇨🇬', '🇨🇳', '🇰🇮', '🇱🇨', '🇵🇹', '🇲🇹', '🇶🇦', '🇸🇮', '🇸🇰', '🇵🇬', '🇸🇬', '🇩🇲', '🇲🇴', '🇹🇴', '🇺🇾', '🇻🇪', '🇼🇸'],
//     ['🇪🇸', '🇭🇰', '🇦🇼', '🇨🇾', '🇮🇹', '🇰🇷', '🇦🇬', '🇸🇲', '🇿🇼'],
//     ['🇧🇪', '🇧🇸', '🇩🇪', '🇫🇷', '🇵🇼', '🇸🇧', '🇳🇷'],
//     ['🇦🇹', '🇨🇦', '🇬🇧', '🇮🇪', '🇯🇵', '🇫🇮', '🇫🇲', '🇵🇷', '🇳🇱', '🇺🇸', '🇲🇭', '🇸🇸'],
//     ['🇦🇺', '🇱🇺', '🇩🇰', '🇸🇪', '🇻🇺', '🇳🇿', '🇹🇻'],
//     ['🇮🇱', '🇧🇧', '🇮🇸', '🇳🇴'],
//     ['🇨🇭']
// ];
