module.exports = [
  { name: 'Iran', code: 'IR', group: 0 },
  { name: 'Sudan', code: 'SD', group: 0 },
  { name: 'Afghanistan', code: 'AF', group: 1 },
  { name: 'Egypt', code: 'EG', group: 1 },
  { name: 'Kyrgyzstan', code: 'KG', group: 1 },
  { name: 'Sri Lanka', code: 'LK', group: 1 },
  { name: 'Burundi', code: 'BI', group: 1 },
  { name: 'Bhutan', code: 'BT', group: 1 },
  { name: 'Georgia', code: 'GE', group: 1 },
  { name: "Lao People's Democratic Republic", code: 'LA', group: 1 },
  { name: 'Lebanon', code: 'LB', group: 1 },
  { name: 'Libya', code: 'LY', group: 1 },
  { name: 'Myanmar', code: 'MM', group: 1 },
  { name: 'Pakistan', code: 'PK', group: 1 },
  { name: 'Sierra Leone', code: 'SL', group: 1 },
  { name: 'Tajikistan', code: 'TJ', group: 1 },
  { name: 'Nepal', code: 'NP', group: 1 },
  { name: 'Suriname', code: 'SR', group: 1 },
  { name: 'Uzbekistan', code: 'UZ', group: 1 },

  { name: 'Bangladesh', code: 'BD', group: 2 },
  { name: 'Burkina Faso', code: 'BF', group: 2 },
  { name: 'Bulgaria', code: 'BG', group: 2 },
  { name: 'Colombia', code: 'CO', group: 2 },
  { name: 'Ethiopia', code: 'ET', group: 2 },
  { name: 'Cambodia', code: 'KH', group: 2 },
  { name: 'Armenia', code: 'AM', group: 2 },
  { name: 'Angola', code: 'AO', group: 2 },
  { name: 'Azerbaijan', code: 'AZ', group: 2 },
  { name: 'Bolivia, Plurinational State of', code: 'BO', group: 2 },
  { name: 'Belarus', code: 'BY', group: 2 },
  { name: 'Algeria', code: 'DZ', group: 2 },
  { name: 'Eritrea', code: 'ER', group: 2 },
  { name: 'Ghana', code: 'GH', group: 2 },
  { name: 'Gambia', code: 'GM', group: 2 },
  { name: 'Guinea-Bissau', code: 'GW', group: 2 },
  { name: 'Guyana', code: 'GY', group: 2 },
  { name: 'Indonesia', code: 'ID', group: 2 },
  { name: 'Kenya', code: 'KE', group: 2 },
  { name: 'Kazakhstan', code: 'KZ', group: 2 },
  { name: 'Moldova, Republic of', code: 'MD', group: 2 },
  { name: 'North Macedonia', code: 'MK', group: 2 },
  { name: 'Mali', code: 'ML', group: 2 },
  { name: 'Malawi', code: 'MW', group: 2 },
  { name: 'Malaysia', code: 'MY', group: 2 },
  { name: 'Mozambique', code: 'MZ', group: 2 },
  { name: 'Nigeria', code: 'NG', group: 2 },
  { name: 'Nicaragua', code: 'NI', group: 2 },
  { name: 'Philippines', code: 'PH', group: 2 },
  { name: 'Paraguay', code: 'PY', group: 2 },
  { name: 'Russian Federation', code: 'RU', group: 2 },
  { name: 'Rwanda', code: 'RW', group: 2 },
  { name: 'Thailand', code: 'TH', group: 2 },
  { name: 'Tanzania, United Republic of', code: 'TZ', group: 2 },
  { name: 'Ukraine', code: 'UA', group: 2 },
  { name: 'Uganda', code: 'UG', group: 2 },
  { name: 'Viet Nam', code: 'VN', group: 2 },
  { name: 'India', code: 'IN', group: 2 },
  { name: 'Madagascar', code: 'MG', group: 2 },
  { name: 'Mongolia', code: 'MN', group: 2 },
  { name: 'Mauritania', code: 'MR', group: 2 },
  { name: 'Mauritius', code: 'MU', group: 2 },
  { name: 'Somalia', code: 'SO', group: 2 },
  { name: 'Timor-Leste', code: 'TL', group: 2 },
  { name: 'Tunisia', code: 'TN', group: 2 },
  { name: 'Türkiye', code: 'TR', group: 2 },
  { name: 'Zambia', code: 'ZM', group: 2 },
  { name: 'Albania', code: 'AL', group: 3 },
  { name: 'Bosnia and Herzegovina', code: 'BA', group: 3 },
  { name: 'Bulgaria', code: 'BG', group: 3 },
  { name: 'Botswana', code: 'BW', group: 3 },
  { name: 'Cameroon', code: 'CM', group: 3 },
  { name: 'Cabo Verde', code: 'CV', group: 3 },
  { name: 'Equatorial Guinea', code: 'GQ', group: 3 },
  { name: 'Honduras', code: 'HN', group: 3 },
  { name: 'Jordan', code: 'JO', group: 3 },
  { name: 'Argentina', code: 'AR', group: 3 },
  { name: 'Bahrain', code: 'BH', group: 3 },
  { name: 'Brazil', code: 'BR', group: 3 },
  { name: 'Congo, Democratic Republic of the', code: 'CD', group: 3 },
  { name: "Côte d'Ivoire", code: 'CI', group: 3 },
  { name: 'Dominican Republic', code: 'DO', group: 3 },
  { name: 'Fiji', code: 'FJ', group: 3 },
  { name: 'Guinea', code: 'GN', group: 3 },
  { name: 'Iraq', code: 'IQ', group: 3 },
  { name: 'Jamaica', code: 'JM', group: 3 },
  { name: 'Comoros', code: 'KM', group: 3 },
  { name: 'Liberia', code: 'LR', group: 3 },
  { name: 'Lesotho', code: 'LS', group: 3 },
  { name: 'Montenegro', code: 'ME', group: 3 },
  { name: 'Oman', code: 'OM', group: 3 },
  { name: 'Panama', code: 'PA', group: 3 },
  { name: 'Mexico', code: 'MX', group: 3 },
  { name: 'Namibia', code: 'NA', group: 3 },
  { name: 'Saudi Arabia', code: 'SA', group: 3 },
  { name: 'Peru', code: 'PE', group: 3 },
  { name: 'Poland', code: 'PL', group: 3 },
  { name: 'Romania', code: 'RO', group: 3 },
  { name: 'Serbia', code: 'RS', group: 3 },
  { name: 'Seychelles', code: 'SC', group: 3 },
  { name: 'Senegal', code: 'SN', group: 3 },
  { name: 'El Salvador', code: 'SV', group: 3 },
  { name: 'Turkmenistan', code: 'TM', group: 3 },
  { name: 'Taiwan, Province of China', code: 'TW', group: 3 },
  { name: 'Brunei Darussalam', code: 'BN', group: 3 },
  { name: 'Morocco', code: 'MA', group: 3 },
  { name: 'Maldives', code: 'MV', group: 3 },
  { name: 'Niger', code: 'NE', group: 3 },
  { name: 'Eswatini', code: 'SZ', group: 3 },
  { name: 'Chad', code: 'TD', group: 3 },
  { name: 'Togo', code: 'TG', group: 3 },
  { name: 'Yemen', code: 'YE', group: 3 },
  { name: 'South Africa', code: 'ZA', group: 3 },

  { name: 'United Arab Emirates', code: 'AE', group: 4 },
  { name: 'Djibouti', code: 'DJ', group: 4 },
  { name: 'Ecuador', code: 'EC', group: 4 },
  { name: 'Guatemala', code: 'GT', group: 4 },
  { name: 'Croatia', code: 'HR', group: 4 },
  { name: 'Lithuania', code: 'LT', group: 4 },
  { name: 'Central African Republic', code: 'CF', group: 4 },
  { name: 'Chile', code: 'CL', group: 4 },
  { name: 'Costa Rica', code: 'CR', group: 4 },
  { name: 'Czechia', code: 'CZ', group: 4 },
  { name: 'Gabon', code: 'GA', group: 4 },
  { name: 'Grenada', code: 'GD', group: 4 },
  { name: 'Haiti', code: 'HT', group: 4 },
  { name: 'Hungary', code: 'HU', group: 4 },
  { name: 'Kuwait', code: 'KW', group: 4 },
  { name: 'Latvia', code: 'LV', group: 4 },
  { name: 'Sao Tome and Principe', code: 'ST', group: 4 },
  { name: 'Trinidad and Tobago', code: 'TT', group: 4 },
  { name: 'Saint Vincent and the Grenadines', code: 'VC', group: 4 },

  { name: 'Estonia', code: 'EE', group: 5 },
  { name: 'Greece', code: 'GR', group: 5 },
  { name: 'Saint Kitts and Nevis', code: 'KN', group: 5 },
  { name: 'Belize', code: 'BZ', group: 5 },
  { name: 'Congo', code: 'CG', group: 5 },
  { name: 'China', code: 'CN', group: 5 },
  { name: 'Kiribati', code: 'KI', group: 5 },
  { name: 'Saint Lucia', code: 'LC', group: 5 },
  { name: 'Portugal', code: 'PT', group: 5 },
  { name: 'Malta', code: 'MT', group: 5 },
  { name: 'Qatar', code: 'QA', group: 5 },
  { name: 'Slovenia', code: 'SI', group: 5 },
  { name: 'Slovakia', code: 'SK', group: 5 },
  { name: 'Papua New Guinea', code: 'PG', group: 5 },
  { name: 'Singapore', code: 'SG', group: 5 },
  { name: 'Dominica', code: 'DM', group: 5 },
  { name: 'Macao', code: 'MO', group: 5 },
  { name: 'Tonga', code: 'TO', group: 5 },
  { name: 'Uruguay', code: 'UY', group: 5 },
  { name: 'Venezuela, Bolivarian Republic of', code: 'VE', group: 5 },
  { name: 'Samoa', code: 'WS', group: 5 },

  { name: 'Spain', code: 'ES', group: 6 },
  { name: 'Hong Kong', code: 'HK', group: 6 },
  { name: 'Aruba', code: 'AW', group: 6 },
  { name: 'Cyprus', code: 'CY', group: 6 },
  { name: 'Italy', code: 'IT', group: 6 },
  { name: 'Korea, Republic of', code: 'KR', group: 6 },
  { name: 'Antigua and Barbuda', code: 'AG', group: 6 },
  { name: 'San Marino', code: 'SM', group: 6 },
  { name: 'Zimbabwe', code: 'ZW', group: 6 },

  { name: 'Belgium', code: 'BE', group: 7 },
  { name: 'Bahamas', code: 'BS', group: 7 },
  { name: 'Germany', code: 'DE', group: 7 },
  { name: 'France', code: 'FR', group: 7 },
  { name: 'Palau', code: 'PW', group: 7 },
  { name: 'Solomon Islands', code: 'SB', group: 7 },
  { name: 'Nauru', code: 'NR', group: 7 },

  { name: 'Austria', code: 'AT', group: 7 },
  { name: 'Canada', code: 'CA', group: 7 },
  {
    name: 'United Kingdom of Great Britain and Northern Ireland',
    code: 'GB',
    group: 7,
  },
  { name: 'Ireland', code: 'IE', group: 7 },
  { name: 'Japan', code: 'JP', group: 7 },
  { name: 'Finland', code: 'FI', group: 7 },
  { name: 'Micronesia, Federated States of', code: 'FM', group: 7 },
  { name: 'Puerto Rico', code: 'PR', group: 7 },
  { name: 'Netherlands', code: 'NL', group: 7 },
  { name: 'United States of America', code: 'US', group: 7 },
  { name: 'Marshall Islands', code: 'MH', group: 7 },
  { name: 'South Sudan', code: 'SS', group: 7 },

  { name: 'Australia', code: 'AU', group: 9 },
  { name: 'Luxembourg', code: 'LU', group: 9 },
  { name: 'Denmark', code: 'DK', group: 9 },
  { name: 'Sweden', code: 'SE', group: 9 },
  { name: 'Vanuatu', code: 'VU', group: 9 },
  { name: 'New Zealand', code: 'NZ', group: 9 },
  { name: 'Tuvalu', code: 'TV', group: 9 },

  { name: 'Israel', code: 'IL', group: 10 },
  { name: 'Barbados', code: 'BB', group: 10 },
  { name: 'Iceland', code: 'IS', group: 10 },
  { name: 'Norway', code: 'NO', group: 10 },
  { name: 'Switzerland', code: 'CH', group: 11 },
];

// export const codes = [
//     ['🇮🇷', '🇸🇩'],

//     ['🇦🇫', '🇪🇬', '🇰🇬', '🇱🇰', '🇧🇮', '🇧🇹', '🇬🇪', '🇱🇦', '🇱🇧', '🇱🇾', '🇲🇲', '🇵🇰', '🇸🇱', '🇹🇯', '🇳🇵', '🇸🇷', '🇺🇿'],

//     [
//         '🇧🇩',
//         '🇧🇫',
//         '🇧🇯',
//         '🇨🇴',
//         '🇪🇹',
//         '🇰🇭',
//         '🇦🇲',
//         '🇦🇴',
//         '🇦🇿',
//         '🇧🇴',
//         '🇧🇾',
//         '🇩🇿',
//         '🇪🇷',
//         '🇬🇭',
//         '🇬🇲',
//         '🇬🇼',
//         '🇬🇾',
//         '🇮🇩',
//         '🇰🇪',
//         '🇰🇿',
//         '🇲🇩',
//         '🇲🇰',
//         '🇲🇱',
//         '🇲🇼',
//         '🇲🇾',
//         '🇲🇿',
//         '🇳🇬',
//         '🇳🇮',
//         '🇵🇭',
//         '🇵🇾',
//         '🇷🇺',
//         '🇷🇼',
//         '🇹🇭',
//         '🇹🇿',
//         '🇺🇦',
//         '🇺🇬',
//         '🇻🇳',
//         '🇮🇳',
//         '🇲🇬',
//         '🇲🇳',
//         '🇲🇷',
//         '🇲🇺',
//         '🇸🇴',
//         '🇹🇱',
//         '🇹🇳',
//         '🇹🇷',
//         '🇿🇲'
//     ],

//     [
//         '🇦🇱',
//         '🇧🇦',
//         '🇧🇬',
//         '🇧🇼',
//         '🇨🇲',
//         '🇨🇻',
//         '🇬🇶',
//         '🇭🇳',
//         '🇯🇴',
//         '🇦🇷',
//         '🇧🇭',
//         '🇧🇷',
//         '🇨🇩',
//         '🇨🇮',
//         '🇩🇴',
//         '🇫🇯',
//         '🇬🇳',
//         '🇮🇶',
//         '🇯🇲',
//         '🇰🇲',
//         '🇱🇷',
//         '🇱🇸',
//         '🇲🇪',
//         '🇴🇲',
//         '🇵🇦',
//         '🇲🇽',
//         '🇳🇦',
//         '🇸🇦',
//         '🇵🇪',
//         '🇵🇱',
//         '🇷🇴',
//         '🇷🇸',
//         '🇸🇨',
//         '🇸🇳',
//         '🇸🇻',
//         '🇹🇲',
//         '🇹🇼',
//         '🇧🇳',
//         '🇲🇦',
//         '🇲🇻',
//         '🇳🇪',
//         '🇸🇿',
//         '🇹🇩',
//         '🇹🇬',
//         '🇾🇪',
//         '🇿🇦'
//     ],
//     ['🇦🇪', '🇩🇯', '🇪🇨', '🇬🇹', '🇭🇷', '🇱🇹', '🇨🇫', '🇨🇱', '🇨🇷', '🇨🇿', '🇬🇦', '🇬🇩', '🇭🇹', '🇭🇺', '🇰🇼', '🇱🇻', '🇸🇹', '🇹🇹', '🇻🇨'],
//     ['🇪🇪', '🇬🇷', '🇰🇳', '🇧🇿', '🇨🇬', '🇨🇳', '🇰🇮', '🇱🇨', '🇵🇹', '🇲🇹', '🇶🇦', '🇸🇮', '🇸🇰', '🇵🇬', '🇸🇬', '🇩🇲', '🇲🇴', '🇹🇴', '🇺🇾', '🇻🇪', '🇼🇸'],
//     ['🇪🇸', '🇭🇰', '🇦🇼', '🇨🇾', '🇮🇹', '🇰🇷', '🇦🇬', '🇸🇲', '🇿🇼'],
//     ['🇧🇪', '🇧🇸', '🇩🇪', '🇫🇷', '🇵🇼', '🇸🇧', '🇳🇷'],
//     ['🇦🇹', '🇨🇦', '🇬🇧', '🇮🇪', '🇯🇵', '🇫🇮', '🇫🇲', '🇵🇷', '🇳🇱', '🇺🇸', '🇲🇭', '🇸🇸'],
//     ['🇦🇺', '🇱🇺', '🇩🇰', '🇸🇪', '🇻🇺', '🇳🇿', '🇹🇻'],
//     ['🇮🇱', '🇧🇧', '🇮🇸', '🇳🇴'],
//     ['🇨🇭']
// ];
