// const single = {
//   object: 'list',
//   data: [
//     {
//       id: 'sub_1MQSsFCx996FZZgasNzJXkMj',
//       object: 'subscription',
//       application: null,
//       application_fee_percent: null,
//       automatic_tax: { enabled: true },
//       billing_cycle_anchor: 1673776295,
//       billing_thresholds: null,
//       cancel_at: null,
//       cancel_at_period_end: false,
//       canceled_at: null,
//       collection_method: 'charge_automatically',
//       created: 1673776295,
//       currency: 'usd',
//       current_period_end: 1676454695,
//       current_period_start: 1673776295,
//       customer: 'cus_NAoVzun66HR3n4',
//       days_until_due: null,
//       default_payment_method: {
//         id: 'pm_1MQSsECx996FZZgam7H9U969',
//         object: 'payment_method',
//         billing_details: {
//           address: {
//             city: null,
//             country: 'BD',
//             line1: null,
//             line2: null,
//             postal_code: null,
//             state: null,
//           },
//           email: 'abutaher267@gmail.com',
//           name: 'Visa',
//           phone: null,
//         },
//         card: {
//           brand: 'visa',
//           checks: {
//             address_line1_check: null,
//             address_postal_code_check: null,
//             cvc_check: 'pass',
//           },
//           country: 'US',
//           exp_month: 12,
//           exp_year: 2025,
//           fingerprint: 'sFM2bvYTMSFnS8KM',
//           funding: 'credit',
//           generated_from: null,
//           last4: '4242',
//           networks: { available: ['visa'], preferred: null },
//           three_d_secure_usage: { supported: true },
//           wallet: null,
//         },
//         created: 1673776294,
//         customer: 'cus_NAoVzun66HR3n4',
//         livemode: false,
//         metadata: {},
//         type: 'card',
//       },
//       default_source: null,
//       default_tax_rates: [],
//       description: null,
//       discount: null,
//       ended_at: null,
//       items: {
//         object: 'list',
//         data: [
//           {
//             id: 'si_NAoVvQo0yr516F',
//             object: 'subscription_item',
//             billing_thresholds: null,
//             created: 1673776295,
//             metadata: {},
//             plan: {
//               id: 'price_1MQSiiCx996FZZgaPa77JyNv',
//               object: 'plan',
//               active: true,
//               aggregate_usage: null,
//               amount: 10000,
//               amount_decimal: '10000',
//               billing_scheme: 'per_unit',
//               created: 1673775704,
//               currency: 'usd',
//               interval: 'month',
//               interval_count: 1,
//               livemode: false,
//               metadata: {},
//               nickname: 'Contrary to popular belief, Lorem Ipsum is not',
//               product: 'prod_NAoL1sJDQVIDm3',
//               tiers_mode: null,
//               transform_usage: null,
//               trial_period_days: null,
//               usage_type: 'licensed',
//             },
//             price: {
//               id: 'price_1MQSiiCx996FZZgaPa77JyNv',
//               object: 'price',
//               active: true,
//               billing_scheme: 'per_unit',
//               created: 1673775704,
//               currency: 'usd',
//               custom_unit_amount: null,
//               livemode: false,
//               lookup_key: null,
//               metadata: {},
//               nickname: 'Contrary to popular belief, Lorem Ipsum is not',
//               product: 'prod_NAoL1sJDQVIDm3',
//               recurring: {
//                 aggregate_usage: null,
//                 interval: 'month',
//                 interval_count: 1,
//                 trial_period_days: null,
//                 usage_type: 'licensed',
//               },
//               tax_behavior: 'exclusive',
//               tiers_mode: null,
//               transform_quantity: null,
//               type: 'recurring',
//               unit_amount: 10000,
//               unit_amount_decimal: '10000',
//             },
//             quantity: 1,
//             subscription: 'sub_1MQSsFCx996FZZgasNzJXkMj',
//             tax_rates: [],
//           },
//         ],
//         has_more: false,
//         total_count: 1,
//         url: '/v1/subscription_items?subscription=sub_1MQSsFCx996FZZgasNzJXkMj',
//       },
//       latest_invoice: 'in_1MQSsFCx996FZZgaoU43wweE',
//       livemode: false,
//       metadata: {},
//       next_pending_invoice_item_invoice: null,
//       on_behalf_of: null,
//       pause_collection: null,
//       payment_settings: {
//         payment_method_options: null,
//         payment_method_types: null,
//         save_default_payment_method: 'off',
//       },
//       pending_invoice_item_interval: null,
//       pending_setup_intent: null,
//       pending_update: null,
//       plan: {
//         id: 'price_1MQSiiCx996FZZgaPa77JyNv',
//         object: 'plan',
//         active: true,
//         aggregate_usage: null,
//         amount: 10000,
//         amount_decimal: '10000',
//         billing_scheme: 'per_unit',
//         created: 1673775704,
//         currency: 'usd',
//         interval: 'month',
//         interval_count: 1,
//         livemode: false,
//         metadata: {},
//         nickname: 'Contrary to popular belief, Lorem Ipsum is not',
//         product: 'prod_NAoL1sJDQVIDm3',
//         tiers_mode: null,
//         transform_usage: null,
//         trial_period_days: null,
//         usage_type: 'licensed',
//       },
//       quantity: 1,
//       schedule: null,
//       start_date: 1673776295,
//       status: 'active',
//       test_clock: null,
//       transfer_data: null,
//       trial_end: null,
//       trial_start: null,
//     },
//   ],
//   has_more: false,
//   url: '/v1/subscriptions',
// };

// const double = {
//   object: 'list',
//   data: [
//     {
//       id: 'sub_1MQSsFCx996FZZgasNzJXkMj',
//       object: 'subscription',
//       application: null,
//       application_fee_percent: null,
//       automatic_tax: { enabled: true },
//       billing_cycle_anchor: 1673776295,
//       billing_thresholds: null,
//       cancel_at: null,
//       cancel_at_period_end: false,
//       canceled_at: null,
//       collection_method: 'charge_automatically',
//       created: 1673776295,
//       currency: 'usd',
//       current_period_end: 1676454695,
//       current_period_start: 1673776295,
//       customer: 'cus_NAoVzun66HR3n4',
//       days_until_due: null,
//       default_payment_method: {
//         id: 'pm_1MQSsECx996FZZgam7H9U969',
//         object: 'payment_method',
//         billing_details: {
//           address: {
//             city: null,
//             country: 'BD',
//             line1: null,
//             line2: null,
//             postal_code: null,
//             state: null,
//           },
//           email: 'abutaher267@gmail.com',
//           name: 'Visa',
//           phone: null,
//         },
//         card: {
//           brand: 'visa',
//           checks: {
//             address_line1_check: null,
//             address_postal_code_check: null,
//             cvc_check: 'pass',
//           },
//           country: 'US',
//           exp_month: 12,
//           exp_year: 2025,
//           fingerprint: 'sFM2bvYTMSFnS8KM',
//           funding: 'credit',
//           generated_from: null,
//           last4: '4242',
//           networks: { available: ['visa'], preferred: null },
//           three_d_secure_usage: { supported: true },
//           wallet: null,
//         },
//         created: 1673776294,
//         customer: 'cus_NAoVzun66HR3n4',
//         livemode: false,
//         metadata: {},
//         type: 'card',
//       },
//       default_source: null,
//       default_tax_rates: [],
//       description: null,
//       discount: null,
//       ended_at: null,
//       items: {
//         object: 'list',
//         data: [
//           {
//             id: 'si_NAoVvQo0yr516F',
//             object: 'subscription_item',
//             billing_thresholds: null,
//             created: 1673776295,
//             metadata: {},
//             plan: {
//               id: 'price_1MQSiiCx996FZZgaPa77JyNv',
//               object: 'plan',
//               active: true,
//               aggregate_usage: null,
//               amount: 10000,
//               amount_decimal: '10000',
//               billing_scheme: 'per_unit',
//               created: 1673775704,
//               currency: 'usd',
//               interval: 'month',
//               interval_count: 1,
//               livemode: false,
//               metadata: {},
//               nickname: 'Contrary to popular belief, Lorem Ipsum is not',
//               product: 'prod_NAoL1sJDQVIDm3',
//               tiers_mode: null,
//               transform_usage: null,
//               trial_period_days: null,
//               usage_type: 'licensed',
//             },
//             price: {
//               id: 'price_1MQSiiCx996FZZgaPa77JyNv',
//               object: 'price',
//               active: true,
//               billing_scheme: 'per_unit',
//               created: 1673775704,
//               currency: 'usd',
//               custom_unit_amount: null,
//               livemode: false,
//               lookup_key: null,
//               metadata: {},
//               nickname: 'Contrary to popular belief, Lorem Ipsum is not',
//               product: 'prod_NAoL1sJDQVIDm3',
//               recurring: {
//                 aggregate_usage: null,
//                 interval: 'month',
//                 interval_count: 1,
//                 trial_period_days: null,
//                 usage_type: 'licensed',
//               },
//               tax_behavior: 'exclusive',
//               tiers_mode: null,
//               transform_quantity: null,
//               type: 'recurring',
//               unit_amount: 10000,
//               unit_amount_decimal: '10000',
//             },
//             quantity: 1,
//             subscription: 'sub_1MQSsFCx996FZZgasNzJXkMj',
//             tax_rates: [],
//           },
//         ],
//         has_more: false,
//         total_count: 1,
//         url: '/v1/subscription_items?subscription=sub_1MQSsFCx996FZZgasNzJXkMj',
//       },
//       latest_invoice: 'in_1MQSsFCx996FZZgaoU43wweE',
//       livemode: false,
//       metadata: {},
//       next_pending_invoice_item_invoice: null,
//       on_behalf_of: null,
//       pause_collection: null,
//       payment_settings: {
//         payment_method_options: null,
//         payment_method_types: null,
//         save_default_payment_method: 'off',
//       },
//       pending_invoice_item_interval: null,
//       pending_setup_intent: null,
//       pending_update: null,
//       plan: {
//         id: 'price_1MQSiiCx996FZZgaPa77JyNv',
//         object: 'plan',
//         active: true,
//         aggregate_usage: null,
//         amount: 10000,
//         amount_decimal: '10000',
//         billing_scheme: 'per_unit',
//         created: 1673775704,
//         currency: 'usd',
//         interval: 'month',
//         interval_count: 1,
//         livemode: false,
//         metadata: {},
//         nickname: 'Contrary to popular belief, Lorem Ipsum is not',
//         product: 'prod_NAoL1sJDQVIDm3',
//         tiers_mode: null,
//         transform_usage: null,
//         trial_period_days: null,
//         usage_type: 'licensed',
//       },
//       quantity: 1,
//       schedule: null,
//       start_date: 1673776295,
//       status: 'active',
//       test_clock: null,
//       transfer_data: null,
//       trial_end: null,
//       trial_start: null,
//     },
//   ],
//   has_more: false,
//   url: '/v1/subscriptions',
// };

// module.exports = { single, double };
