const { model, Schema, Types } = require('mongoose');
module.exports = model(
  'Payment',
  new Schema({
    userId: { type: Types.ObjectId, required: true },
    subscription: { type: String, required: true },
    amount: { type: Number, required: true },
    currency: { type: String, required: true },
    email: { type: String, required: true },
    phone: String,
    name: { type: String, required: true },
    invoice: { type: String, required: true },
    payment_status: { type: String, required: true },
    payment_method_types: Array,
    status: { type: String, required: true },
    current_period_start: { type: Number, required: true },
    current_period_end: { type: Number, required: true },
    quantity: { type: Number, required: true },
    customer: { type: String, required: true },
    product: String,
  })
);

// const subs = {
//   object: 'list',
//   data: [
//     {
//       id: 'sub_1MQcC0Cx996FZZga2kd1JlOx',
//       object: 'subscription',
//       application: null,
//       application_fee_percent: null,
//       automatic_tax: { enabled: false },
//       billing_cycle_anchor: 1673812116,
//       billing_thresholds: null,
//       cancel_at: null,
//       cancel_at_period_end: false,
//       canceled_at: null,
//       collection_method: 'charge_automatically',
//       created: 1673812116,
//       currency: 'usd',
//       current_period_end: 1676490516, //1673898484
//       current_period_start: 1673812116,
//       customer: 'cus_NAy7dnYm7wmDIb',
//       days_until_due: null,
//       default_payment_method: {
//         id: 'pm_1MQcBzCx996FZZgatmM7NDO5',
//         object: 'payment_method',
//         billing_details: {
//           address: {
//             city: null,
//             country: 'BD',
//             line1: null,
//             line2: null,
//             postal_code: null,
//             state: null,
//           },
//           email: 'nisot79655@tingn.com',
//           name: 'Mastarcard',
//           phone: null,
//         },
//         card: {
//           brand: 'visa',
//           checks: {
//             address_line1_check: null,
//             address_postal_code_check: null,
//             cvc_check: 'pass',
//           },
//           country: 'US',
//           exp_month: 12,
//           exp_year: 2025,
//           fingerprint: 'sFM2bvYTMSFnS8KM',
//           funding: 'credit',
//           generated_from: null,
//           last4: '4242',
//           networks: { available: ['visa'], preferred: null },
//           three_d_secure_usage: { supported: true },
//           wallet: null,
//         },
//         created: 1673812115,
//         customer: 'cus_NAy7dnYm7wmDIb',
//         livemode: false,
//         metadata: {},
//         type: 'card',
//       },
//       default_source: null,
//       default_tax_rates: [],
//       description: null,
//       discount: null,
//       ended_at: null,
//       items: {
//         object: 'list',
//         data: [
//           {
//             id: 'si_NAy8da3WWxeVjK',
//             object: 'subscription_item',
//             billing_thresholds: null,
//             created: 1673812116,
//             metadata: {},
//             plan: {
//               id: 'price_1MQSiiCx996FZZgaPa77JyNv',
//               object: 'plan',
//               active: true,
//               aggregate_usage: null,
//               amount: 10000,
//               amount_decimal: '10000',
//               billing_scheme: 'per_unit',
//               created: 1673775704,
//               currency: 'usd',
//               interval: 'month',
//               interval_count: 1,
//               livemode: false,
//               metadata: {},
//               nickname: 'Contrary to popular belief, Lorem Ipsum is not',
//               product: 'prod_NAoL1sJDQVIDm3',
//               tiers_mode: null,
//               transform_usage: null,
//               trial_period_days: null,
//               usage_type: 'licensed',
//             },
//             price: {
//               id: 'price_1MQSiiCx996FZZgaPa77JyNv',
//               object: 'price',
//               active: true,
//               billing_scheme: 'per_unit',
//               created: 1673775704,
//               currency: 'usd',
//               custom_unit_amount: null,
//               livemode: false,
//               lookup_key: null,
//               metadata: {},
//               nickname: 'Contrary to popular belief, Lorem Ipsum is not',
//               product: 'prod_NAoL1sJDQVIDm3',
//               recurring: {
//                 aggregate_usage: null,
//                 interval: 'month',
//                 interval_count: 1,
//                 trial_period_days: null,
//                 usage_type: 'licensed',
//               },
//               tax_behavior: 'exclusive',
//               tiers_mode: null,
//               transform_quantity: null,
//               type: 'recurring',
//               unit_amount: 10000,
//               unit_amount_decimal: '10000',
//             },
//             quantity: 1,
//             subscription: 'sub_1MQcC0Cx996FZZga2kd1JlOx',
//             tax_rates: [],
//           },
//         ],
//         has_more: false,
//         total_count: 1,
//         url: '/v1/subscription_items?subscription=sub_1MQcC0Cx996FZZga2kd1JlOx',
//       },
//       latest_invoice: 'in_1MQcC0Cx996FZZgaS13LQ8Jt',
//       livemode: false,
//       metadata: {},
//       next_pending_invoice_item_invoice: null,
//       on_behalf_of: null,
//       pause_collection: null,
//       payment_settings: {
//         payment_method_options: null,
//         payment_method_types: null,
//         save_default_payment_method: 'off',
//       },
//       pending_invoice_item_interval: null,
//       pending_setup_intent: null,
//       pending_update: null,
//       plan: {
//         id: 'price_1MQSiiCx996FZZgaPa77JyNv',
//         object: 'plan',
//         active: true,
//         aggregate_usage: null,
//         amount: 10000,
//         amount_decimal: '10000',
//         billing_scheme: 'per_unit',
//         created: 1673775704,
//         currency: 'usd',
//         interval: 'month',
//         interval_count: 1,
//         livemode: false,
//         metadata: {},
//         nickname: 'Contrary to popular belief, Lorem Ipsum is not',
//         product: 'prod_NAoL1sJDQVIDm3',
//         tiers_mode: null,
//         transform_usage: null,
//         trial_period_days: null,
//         usage_type: 'licensed',
//       },
//       quantity: 1,
//       schedule: null,
//       start_date: 1673812116,
//       status: 'active',
//       test_clock: null,
//       transfer_data: null,
//       trial_end: null,
//       trial_start: null,
//     },
//   ],
//   has_more: false,
//   url: '/v1/subscriptions',
// };

// const hook = {
//   id: 'cs_test_a15GY9kHKmsp0b0hJwlT1lAx4MUKeGuwjbnHoZ6VhAMx3xkprLgqGRaoWF',
//   object: 'checkout.session',
//   after_expiration: null,
//   allow_promotion_codes: null,
//   amount_subtotal: 10000,
//   amount_total: 10000,
//   automatic_tax: { enabled: false, status: null },
//   billing_address_collection: null,
//   cancel_url: 'http://localhost:3000/deal',
//   client_reference_id: null,
//   consent: null,
//   consent_collection: null,
//   created: 1673812084,
//   currency: 'usd',
//   custom_text: { shipping_address: null, submit: null },
//   customer: 'cus_NAy7dnYm7wmDIb',
//   customer_creation: null,
//   customer_details: {
//     address: {
//       city: null,
//       country: 'BD',
//       line1: null,
//       line2: null,
//       postal_code: null,
//       state: null,
//     },
//     email: 'nisot79655@tingn.com',
//     name: 'Mastarcard',
//     phone: null,
//     tax_exempt: 'none',
//     tax_ids: [],
//   },
//   customer_email: null,
//   expires_at: 1673898484,
//   invoice: 'in_1MQcC0Cx996FZZgaS13LQ8Jt',
//   invoice_creation: null,
//   livemode: false,
//   locale: null,
//   metadata: {},
//   mode: 'subscription',
//   payment_intent: null,
//   payment_link: null,
//   payment_method_collection: 'always',
//   payment_method_options: null,
//   payment_method_types: ['card'],
//   payment_status: 'paid',
//   phone_number_collection: { enabled: false },
//   recovered_from: null,
//   setup_intent: null,
//   shipping_address_collection: null,
//   shipping_cost: null,
//   shipping_details: null,
//   shipping_options: [],
//   status: 'complete',
//   submit_type: null,
//   subscription: 'sub_1MQcC0Cx996FZZga2kd1JlOx',
//   success_url: 'http://localhost:3000/deal',
//   total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
//   url: null,
// };

let fkdjfkd = {
  // subscription: 'subscription', //new
  // amount: 'amount_subtotal',
  // customer: '',
  // created: 1673812084,
  // currency: 'usd',
  // customer_details:{email, phone,name},
  // invoice: '', // new
  // payment_status: '', //new
  // status: '', //new
};

// let rdOne = {
//   id: 'cs_test_a1p0XfmjIxfiOSt1gdsNAYlo17aYCt4YdALGXXlxyhSeE1vKIyLDve3FBQ',
//   object: 'checkout.session',
//   after_expiration: null,
//   allow_promotion_codes: null,
//   amount_subtotal: 10000,
//   amount_total: 10000,
//   automatic_tax: { enabled: false, status: null },
//   billing_address_collection: null,
//   cancel_url: 'http://localhost:3000/deal',
//   client_reference_id: null,
//   consent: null,
//   consent_collection: null,
//   created: 1673814020,
//   currency: 'usd',
//   custom_text: { shipping_address: null, submit: null },
//   customer: 'cus_NAy7dnYm7wmDIb',
//   customer_creation: null,
//   customer_details: {
//     address: {
//       city: null,
//       country: 'BD',
//       line1: null,
//       line2: null,
//       postal_code: null,
//       state: null,
//     },
//     email: 'nisot79655@tingn.com',
//     name: 'Mastarcard',
//     phone: null,
//     tax_exempt: 'none',
//     tax_ids: [],
//   },
//   customer_email: null,
//   expires_at: 1673900419,
//   invoice: 'in_1MQcgmCx996FZZgaCPq03Uq7',
//   invoice_creation: null,
//   livemode: false,
//   locale: null,
//   metadata: {},
//   mode: 'subscription',
//   payment_intent: null,
//   payment_link: null,
//   payment_method_collection: 'always',
//   payment_method_options: null,
//   payment_method_types: ['card'],
//   payment_status: 'paid',
//   phone_number_collection: { enabled: false },
//   recovered_from: null,
//   setup_intent: null,
//   shipping_address_collection: null,
//   shipping_cost: null,
//   shipping_details: null,
//   shipping_options: [],
//   status: 'complete',
//   submit_type: null,
//   subscription: 'sub_1MQcgmCx996FZZgaRPwWEwTt',
//   success_url: 'http://localhost:3000/deal',
//   total_details: { amount_discount: 0, amount_shipping: 0, amount_tax: 0 },
//   url: null,
// };
